---
####################################################
#          ModuleBuilder Configuration             #
####################################################

CopyPaths:
  - en-US
Encoding: UTF8
VersionedOutputDirectory: true

####################################################
#       Sampler Pipeline Configuration             #
####################################################
# Defining 'Workflows' (suite of InvokeBuild tasks) to be run using their alias
BuildWorkflow:
  ".": # "." is the default Invoke-Build workflow. It is called when no -Tasks is specified to the build.ps1
    #- build
    - test

  build:
    - Clean
    - Build_Module_ModuleBuilder
    #- Create_changelog_release_output

  pack:
    - build
    - package_module_nupkg

  # Defining test task to be run when invoking `./build.ps1 -Tasks test`
  test:
    - Pester_Tests_Stop_On_Fail
    - Pester_if_Code_Coverage_Under_Threshold

  publish:
    - publish_module_to_gallery
    - Publish_Release_To_GitHub

####################################################
#       PESTER  Configuration                      #
####################################################

Pester:
  # Pester Advanced configuration.
  # If a key is not set it will be using Sampler pipeline default value.
  Configuration:
    Run:
      Path:
        #- tests/QA/
        - tests/QA/module.tests.ps1
        #- tests/Unit/
        #- tests/Unit/Get-PFBuilding.Tests.ps1
        #- tests/Unit/Get-PF*.Tests.ps1
        #- tests/Integration
      ExcludePath:
        #- tests/Unit/Get-PFStatus.Tests.ps1
    Filter:
      Tag:
        - Changelog
        - Module
        #- FunctionalQuality2
      #- helpQuality #TODO #Get-UMSDevice as template

      ExcludeTag:

    Output:
      Verbosity: Detailed #Normal
    # CodeCoverage:
    #   Path:
    #   # Tests for New-PF* in ToDo
    #   #- source/Public/
    #   #- source/Public/Get-UMSDevice.ps1
    #   #- source/Public/Get-UMS*.ps1
    #   #- source/Public/Update-UMS*.ps1
    #   #- source/Public/Remove-UMS*.ps1
    #   OutputFormat: "JaCoCo"
    #   CoveragePercentTarget: 85
    #   OutputPath: "tests/Data/coverage.xml"
    #   OutputEncoding:
    #   ExcludeTests:
    # TestResult:
    #   OutputFormat: NUnitXML
    #   OutputPath:
    #   OutputEncoding:
    #   TestSuiteName:

# Import ModuleBuilder tasks from a specific PowerShell module using the build
# task's alias. Wildcard * can be used to specify all tasks that has a similar
# prefix and or suffix. The module contain the task must be added as a required
# module in the file RequiredModules.psd1.
ModuleBuildTasks:
  Sampler:
    - "*.build.Sampler.ib.tasks"
  Sampler.GitHubTasks:
    - "*.ib.tasks"

# Invoke-Build Header to be used to 'decorate' the terminal output of the tasks.
TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitHubConfig:
  GitHubFilesToAdd:
    - "CHANGELOG.md"
  GitHubConfigUserName: falkheiland
  GitHubConfigUserEmail: falkheiland@users.noreply.github.com
  UpdateChangelogOnPrerelease: false
